# Generated by Django 4.0.3 on 2023-11-05 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
    ]
