# Generated by Django 4.0.3 on 2023-11-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
